name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: |
        ./gradlew compileJava
        ./gradlew processResources
        ./gradlew jar
        ./gradlew execJar
    - name: Upload the artifact
      uses: actions/upload-artifact@v3
      with:
        name: HMMRATAC-snapshot
        path: build/libs/HMMRATAC-snapshot-exec.jar
